title: My blog
description: Minimal blog for papers, math, code, and artwork!
theme: minima

markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: mathjax
  input: GFM

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed


category_tree:
  paper-review:
    title: Paper Review
    children:
      - explainable-ai
      - generative-ai
      - computer-vision

  project:
    title: Project
    children:
      - project
